[versions]
shadow = "8.3.0"
blossom = "1.3.1"
licenser = "0.6.1"

[plugins]
blossom = { id = "net.kyori.blossom", version.ref = "blossom" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
licenser = { id = "org.cadixdev.licenser", version.ref = "licenser" }